const pricing = {
  frequencies: [
    { value: "monthly", label: "Monthly", priceSuffix: "/month" },
    { value: "annually", label: "Annually", priceSuffix: "/year" },
  ],
  tiers: [
    {
      name: "Pro",
      id: "tier-pro",
      productId: 170210,
      variantIdYearly: 223714,
      variantIdMonthly: 217932,
      btnTitle: "Get Started",
      href: "#",
      price: { monthly: 40, annually: 140 },
      description: "Perfect feet for startup",
      features: [
        "Featured Label",
        "Featured Label",
        "Featured Label",
        "Featured Label",
      ],
      mostPopular: false,
    },
    {
      name: "Business",
      id: "tier-business",
      btnTitle: "Get Started",
      productId: 170208,
      variantIdYearly: 217927,
      variantIdMonthly: 223713,
      href: "#",
      price: { monthly: 50, annually: 150 },
      description: "Perfect feet for startup",
      features: [
        "Featured Label",
        "Featured Label",
        "Featured Label",
        "Featured Label",
      ],
      mostPopular: true,
    },
    {
      name: "Agency",
      id: "tier-agency",
      btnTitle: "Get Started",
      productId: 170212,
      variantIdYearly: 217934,
      variantIdMonthly: 218039,
      href: "#",
      price: { monthly: 60, annually: 160 },
      description: "Perfect feet for startup",
      features: [
        "Featured Label",
        "Featured Label",
        "Featured Label",
        "Featured Label",
      ],
      mostPopular: false,
    },
  ],
};
